// src/ui/shared/parameterDefinitions.ts
//! Unified Parameter Schema for Develop and Adjustment Controls

export interface ParameterDefinition {
  id: string;
  label: string;
  min: number;
  max: number;
  step: number;
  fineStep: number;
  defaultValue: number;
  unit?: string;
  formatter?: (val: number) => string;
}

export const PARAM_DEFINITIONS: Record<string, ParameterDefinition> = {
  exposure: {
    id: 'exposure',
    label: '曝光',
    min: -5.0,
    max: 5.0,
    step: 0.05,
    fineStep: 0.01,
    defaultValue: 0.0,
    unit: 'EV',
    formatter: (v) => (v > 0 ? `+${v.toFixed(2)}` : v.toFixed(2)),
  },
  contrast: {
    id: 'contrast',
    label: '对比度',
    min: -100,
    max: 100,
    step: 1,
    fineStep: 0.2,
    defaultValue: 0,
    formatter: (v) => (v > 0 ? `+${Math.round(v)}` : `${Math.round(v)}`),
  },
  highlights: {
    id: 'highlights',
    label: '高光',
    min: -100,
    max: 100,
    step: 1,
    fineStep: 0.2,
    defaultValue: 0,
    formatter: (v) => (v > 0 ? `+${Math.round(v)}` : `${Math.round(v)}`),
  },
  shadows: {
    id: 'shadows',
    label: '阴影',
    min: -100,
    max: 100,
    step: 1,
    fineStep: 0.2,
    defaultValue: 0,
    formatter: (v) => (v > 0 ? `+${Math.round(v)}` : `${Math.round(v)}`),
  },
  whites: {
    id: 'whites',
    label: '白色',
    min: -100,
    max: 100,
    step: 1,
    fineStep: 0.2,
    defaultValue: 0,
    formatter: (v) => (v > 0 ? `+${Math.round(v)}` : `${Math.round(v)}`),
  },
  blacks: {
    id: 'blacks',
    label: '黑色',
    min: -100,
    max: 100,
    step: 1,
    fineStep: 0.2,
    defaultValue: 0,
    formatter: (v) => (v > 0 ? `+${Math.round(v)}` : `${Math.round(v)}`),
  },
  temperature: {
    id: 'temperature',
    label: '色温',
    min: 2000,
    max: 12000,
    step: 50,
    fineStep: 10,
    defaultValue: 5500,
    unit: 'K',
    formatter: (v) => `${Math.round(v)}K`,
  },
  tint: {
    id: 'tint',
    label: '色调',
    min: -150,
    max: 150,
    step: 1,
    fineStep: 0.2,
    defaultValue: 0,
    formatter: (v) => (v > 0 ? `+${Math.round(v)}` : `${Math.round(v)}`),
  },
  texture: {
    id: 'texture',
    label: '纹理',
    min: -100,
    max: 100,
    step: 1,
    fineStep: 0.2,
    defaultValue: 0,
    formatter: (v) => (v > 0 ? `+${Math.round(v)}` : `${Math.round(v)}`),
  },
  clarity: {
    id: 'clarity',
    label: '清晰度',
    min: -100,
    max: 100,
    step: 1,
    fineStep: 0.2,
    defaultValue: 0,
    formatter: (v) => (v > 0 ? `+${Math.round(v)}` : `${Math.round(v)}`),
  },
  dehaze: {
    id: 'dehaze',
    label: '去薄雾',
    min: -100,
    max: 100,
    step: 1,
    fineStep: 0.2,
    defaultValue: 0,
    formatter: (v) => (v > 0 ? `+${Math.round(v)}` : `${Math.round(v)}`),
  },
  vibrance: {
    id: 'vibrance',
    label: '自然饱和度',
    min: -100,
    max: 100,
    step: 1,
    fineStep: 0.2,
    defaultValue: 0,
    formatter: (v) => (v > 0 ? `+${Math.round(v)}` : `${Math.round(v)}`),
  },
  saturation: {
    id: 'saturation',
    label: '饱和度',
    min: -100,
    max: 100,
    step: 1,
    fineStep: 0.2,
    defaultValue: 0,
    formatter: (v) => (v > 0 ? `+${Math.round(v)}` : `${Math.round(v)}`),
  },
  sharpenAmount: {
    id: 'sharpenAmount',
    label: '锐化强度',
    min: 0,
    max: 150,
    step: 1,
    fineStep: 0.5,
    defaultValue: 25,
    formatter: (v) => `${Math.round(v)}`,
  },
  sharpenRadius: {
    id: 'sharpenRadius',
    label: '锐化半径',
    min: 0.5,
    max: 3.0,
    step: 0.1,
    fineStep: 0.05,
    defaultValue: 1.0,
    unit: 'px',
    formatter: (v) => `${v.toFixed(1)} px`,
  },
  sharpenThreshold: {
    id: 'sharpenThreshold',
    label: '锐化阈值',
    min: 0,
    max: 25,
    step: 1,
    fineStep: 0.2,
    defaultValue: 0,
    formatter: (v) => `${Math.round(v)}`,
  },
  lumaDenoise: {
    id: 'lumaDenoise',
    label: '明度降噪',
    min: 0,
    max: 100,
    step: 1,
    fineStep: 0.2,
    defaultValue: 0,
    formatter: (v) => `${Math.round(v)}`,
  },
  chromaDenoise: {
    id: 'chromaDenoise',
    label: '色彩降噪',
    min: 0,
    max: 100,
    step: 1,
    fineStep: 0.2,
    defaultValue: 15,
    formatter: (v) => `${Math.round(v)}`,
  },
  vignetteAmount: {
    id: 'vignetteAmount',
    label: '晕影数量',
    min: -100,
    max: 100,
    step: 1,
    fineStep: 0.5,
    defaultValue: 0,
    formatter: (v) => (v > 0 ? `+${Math.round(v)}` : `${Math.round(v)}`),
  },
  vignetteMidpoint: {
    id: 'vignetteMidpoint',
    label: '晕影范围',
    min: 0,
    max: 100,
    step: 1,
    fineStep: 0.5,
    defaultValue: 50,
    formatter: (v) => `${Math.round(v)}`,
  },
  hslHue: {
    id: 'hslHue',
    label: '色相偏移',
    min: -100,
    max: 100,
    step: 1,
    fineStep: 0.2,
    defaultValue: 0,
    formatter: (v) => (v > 0 ? `+${Math.round(v)}` : `${Math.round(v)}`),
  },
  hslSat: {
    id: 'hslSat',
    label: '饱和度',
    min: -100,
    max: 100,
    step: 1,
    fineStep: 0.2,
    defaultValue: 0,
    formatter: (v) => (v > 0 ? `+${Math.round(v)}` : `${Math.round(v)}`),
  },
  hslLum: {
    id: 'hslLum',
    label: '明度',
    min: -100,
    max: 100,
    step: 1,
    fineStep: 0.2,
    defaultValue: 0,
    formatter: (v) => (v > 0 ? `+${Math.round(v)}` : `${Math.round(v)}`),
  },
};
